### ISSUE TITLE
libicu linking errors

### ISSUE THREAD

**Issue by yonas** [wasmerio/winterjs#60] opened 2024-03-28 22:36 UTC
libicu linker errors: https://github.com/servo/mozjs/issues/461

OS: Ubuntu 23.04
Rust: 1.79.0-nightly (499a61ce7 2024-03-26)
winterjs: 0bf0331

**Comment by yonas** [comment] 2024-03-29 18:17
https://github.com/servo/mozjs/issues/461 got closed becase "Winterjs uses custom fork of mozjs: https://github.com/wasmerio/mozjs/tree/wasi-gecko, that is heavily modified, so I think this should be reported to them."

The build log can be found here: https://github.com/servo/mozjs/files/14805705/typescript.txt

**Comment by Arshia001** [comment] 2024-04-01 12:11
Hi @yonas, thanks for reporting this! I believe this is caused by a misconfiguration in our build scripts, which I'm working on right now. Please follow the discussion in #47, I'll post a fix there shortly. I'll close this issue for now, but feel free to reopen if the issue persists after #47 is resolved.

**Closed** 2024-04-01 12:53 UTC
