### ISSUE TITLE
macos install error

### ISSUE THREAD

**Issue by 5-23** [wasmerio/winterjs#64] opened 2024-04-04 10:17 UTC
```shell
error: failed to run custom build command for `mozjs_sys v0.68.2 (https://github.com/wasmerio/mozjs.git?branch=wasi-gecko#91349dc0)`

Caused by:
  process didn't exit successfully: `/var/folders/gm/zk1pj50164z7ywbf71l0wt4w0000gn/T/cargo-installK8vtKC/release/build/mozjs_sys-e8e4101caa0c615d/build-script-build` (exit status: 101)
  --- stdout
  cargo:outdir=/var/folders/gm/zk1pj50164z7ywbf71l0wt4w0000gn/T/cargo-installK8vtKC/release/build/mozjs_sys-efaa4d57947c31e7/out/build
  [[ '/Users/dev523/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/91349dc/mozjs-sys'/mozjs/js/src/configure -ot '/Users/dev523/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/91349dc/mozjs-sys'/mozjs/js/src/configure.in ]] && touch '/Users/dev523/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/91349dc/mozjs-sys'/mozjs/js/src/configure || true
  [[ '/Users/dev523/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/91349dc/mozjs-sys'/mozjs/js/src/old-configure -ot '/Users/dev523/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/91349dc/mozjs-sys'/mozjs/js/src/old-configure.in ]] && touch '/Users/dev523/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/91349dc/mozjs-sys'/mozjs/js/src/old-configure || true
  ! [[ '/Users/dev523/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/91349dc/mozjs-sys'/mozjs/js/src/configure.in -ot '/Users/dev523/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/91349dc/mozjs-sys'/mozjs/js/src/configure ]] && touch '/Users/dev523/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/91349dc/mozjs-sys'/mozjs/js/src/configure || true
  ! [[ '/Users/dev523/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/91349dc/mozjs-sys'/mozjs/js/src/old-configure.in -ot '/Users/dev523/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/91349dc/mozjs-sys'/mozjs/js/src/old-configure ]] && touch '/Users/dev523/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/91349dc/mozjs-sys'/mozjs/js/src/old-configure || true
  if [[ '/Users/dev523/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/91349dc/mozjs-sys'/mozjs/js/src/configure -nt config.status ]] ; then \
  	  CC="cc" CFLAGS="" \
  	  CPP="cc -E" CPPFLAGS="-I/Users/dev523/.cargo/registry/src/index.crates.io-6f17d22bba15001f/encoding_c_mem-0.2.6/include " \
  	  CXX="c++" CXXFLAGS="-stdlib=libc++" \
  	  AS="" AR="ar" \
  	  '/Users/dev523/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/91349dc/mozjs-sys'/mozjs/js/src/configure --disable-jemalloc --disable-js-shell --disable-tests --disable-export-js --disable-shared-js --build-backends=RecursiveMake --enable-js-streams || (cat config.log && exit 1) ; \
  	fi

  --- stderr
  Traceback (most recent call last):
    File "/Users/dev523/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/91349dc/mozjs-sys/mozjs/js/src/../../configure.py", line 35, in <module>
      from mozbuild.configure import TRACE, ConfigureSandbox
    File "/Users/dev523/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/91349dc/mozjs-sys/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 18, in <module>
      from six.moves import builtins as __builtin__
  ModuleNotFoundError: No module named 'six.moves'
  cat: config.log: No such file or directory
  make: *** [maybe-configure] Error 1
  thread 'main' panicked at /Users/dev523/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/91349dc/mozjs-sys/build.rs:272:5:
  assertion failed: result.success()
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `winterjs v1.0.0 (https://github.com/wasmerio/winterjs#bb4a677f)`, intermediate artifacts can be found at `/var/folders/gm/zk1pj50164z7ywbf71l0wt4w0000gn/T/cargo-installK8vtKC`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path
```

**Comment by Arshia001** [comment] 2024-04-04 13:43
Hi @5-23, thanks for reporting this issue! This is a duplicate of #49, so I'll close this one.

**Closed by Arshia001** 2024-04-04 13:43 UTC
